version: "3.8"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  product-service:
    build: ./product-service
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"