version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    env_file:
      - ./auth-service/.env
    networks:
      - mynetwork

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "5002:5000"
    depends_on:
      - mongodb
    env_file:
      - ./product-service/.env
    networks:
      - mynetwork

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "5003:5000"
    depends_on:
      - mongodb
    env_file:
      - ./order-service/.env
    networks:
      - mynetwork

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "5004:5000"
    depends_on:
      - mongodb
    env_file:
      - ./payment-service/.env
    networks:
      - mynetwork

volumes:
  mongodb_data:

networks:
  mynetwork:
    driver: bridge