version: "3.8"

services:      
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    env_file:
      - ./auth-service/.env
    networks:
      - mynetwork

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "5002:5000"
    depends_on:
      - mongodb
    env_file:
      - ./product-service/.env
    networks:
      - mynetwork

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "5003:5000"
    depends_on:
      - mongodb
    env_file:
      - ./order-service/.env
    networks:
      - mynetwork

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "5004:5000"
    depends_on:
      - mongodb
    env_file:
      - ./payment-service/.env
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"  # Prometheus UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount Prometheus config file
    networks:
      - mynetwork
    depends_on:
      - auth-service
      - product-service
      - order-service
      - payment-service

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"  # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set the Grafana admin password
    volumes:
      - grafana_data:/var/lib/grafana  # Persistent storage for Grafana data
    networks:
      - mynetwork
    depends_on:
      - prometheus

volumes:
  mongodb_data:
  grafana_data:

networks:
  mynetwork:
    driver: bridge
